PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_account (id INTEGER PRIMARY KEY CHECK(id=1), google_id TEXT, email TEXT, name TEXT, picture_url TEXT, channel_id TEXT, channel_name TEXT, channel_thumb TEXT, subscriber_count INTEGER DEFAULT 0, video_count INTEGER DEFAULT 0, access_token TEXT, refresh_token TEXT, expiry_date INTEGER);
CREATE TABLE IF NOT EXISTS channels (id INTEGER PRIMARY KEY AUTOINCREMENT, youtube_channel_id TEXT UNIQUE NOT NULL, channel_name TEXT, channel_handle TEXT, thumbnail_url TEXT, uploads_playlist_id TEXT, interval_hours INTEGER DEFAULT 6, auto_upload INTEGER DEFAULT 0, quality TEXT DEFAULT 'best', title_template TEXT DEFAULT '{original_title}', desc_template TEXT DEFAULT '{original_description}', extra_tags TEXT DEFAULT '', privacy TEXT DEFAULT 'unlisted', ignore_shorts INTEGER DEFAULT 0, only_shorts INTEGER DEFAULT 0, is_active INTEGER DEFAULT 1, backfill_done INTEGER DEFAULT 0, last_checked_at TEXT, last_error TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS synced_videos (id INTEGER PRIMARY KEY AUTOINCREMENT, channel_id INTEGER REFERENCES channels(id) ON DELETE CASCADE, source_video_id TEXT NOT NULL, source_title TEXT, source_url TEXT, source_channel_name TEXT, downloaded_path TEXT, thumbnail_path TEXT, uploaded_video_id TEXT, uploaded_url TEXT, upload_type TEXT DEFAULT 'single', privacy TEXT DEFAULT 'unlisted', status TEXT DEFAULT 'pending', error_message TEXT, attempts INTEGER DEFAULT 0, file_size_mb REAL, clip_id INTEGER, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')), UNIQUE(channel_id, source_video_id, upload_type));
CREATE TABLE IF NOT EXISTS clips (id INTEGER PRIMARY KEY AUTOINCREMENT, source_video_id TEXT, source_title TEXT, source_path TEXT, start_time REAL NOT NULL, end_time REAL NOT NULL, score INTEGER, suggested_title TEXT, hook TEXT, hashtags TEXT, reason TEXT, local_path TEXT, thumbnail_path TEXT, status TEXT DEFAULT 'pending', uploaded_video_id TEXT, uploaded_url TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS upload_history (id INTEGER PRIMARY KEY AUTOINCREMENT, source_url TEXT, source_title TEXT, uploaded_id TEXT, uploaded_url TEXT, upload_type TEXT, status TEXT, error TEXT, size_mb REAL, duration_sec REAL, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS job_log (id INTEGER PRIMARY KEY AUTOINCREMENT, job_type TEXT, ref_id INTEGER, level TEXT, message TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_synced_videos_status ON synced_videos(status); CREATE INDEX IF NOT EXISTS idx_clips_status ON clips(status); CREATE INDEX IF NOT EXISTS idx_channels_active ON channels(is_active);
