#!/usr/bin/env bash
# Muscle Paradise installer — Linux / macOS.
#
# Installs the local-first core plus the prebuilt Studio shell into
# ~/.muscle-paradise and leaves a single `mp` launcher on your PATH.
# Nothing is uploaded anywhere: the app talks to a local SQLite file.
#
#   ./install.sh                 # install
#   MP_PREFIX=/opt/mp ./install.sh
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${MP_PREFIX:-$HOME/.muscle-paradise}"
PORT="${MP_PORT:-8751}"
WITH_TESTS=0
for arg in "$@"; do
  case "$arg" in
    --with-tests) WITH_TESTS=1 ;;
    *) printf 'usage: ./install.sh [--with-tests]\n' >&2; exit 2 ;;
  esac
done

say() { printf '\033[1;36m==>\033[0m %s\n' "$1"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$1" >&2; exit 1; }

# --- 1. find a Python 3.10+ -------------------------------------------------
PY=""
for cand in python3.13 python3.12 python3.11 python3; do
  if command -v "$cand" >/dev/null 2>&1; then
    if "$cand" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)'; then
      PY="$(command -v "$cand")"; break
    fi
  fi
done
[ -n "$PY" ] || die "Python 3.10 or newer is required but was not found."
say "Using $($PY -V) at $PY"

# --- 2. lay out the prefix --------------------------------------------------
say "Installing into $PREFIX"
mkdir -p "$PREFIX/bin" "$PREFIX/app"
cp -R "$HERE/backend/." "$PREFIX/app/backend/"
# Runtime assets resolved by the app as backend/../../ (parents[3]):
#   app/assets/fonts/PersianSans-Regular.ttf  -> Persian PDF text
#   app/packs/exercises_seed.json             -> exercise library
cp -R "$HERE/assets" "$PREFIX/app/assets"
cp -R "$HERE/packs"  "$PREFIX/app/packs"
rm -rf "$PREFIX/app/studio"
cp -R "$HERE/studio-dist" "$PREFIX/app/studio"

# --- 3. virtualenv + dependencies ------------------------------------------
if [ ! -x "$PREFIX/venv/bin/python" ]; then
  say "Creating virtualenv"
  "$PY" -m venv "$PREFIX/venv"
fi
VPY="$PREFIX/venv/bin/python"

# Runtime deps by default; --with-tests adds pytest + PyMuPDF so `mp test` runs.
REQS="requirements-runtime.txt"
if [ "$WITH_TESTS" -eq 1 ]; then REQS="requirements.txt"; fi

# Offline first (bundled wheels are cp311/manylinux); fall back to PyPI so the
# installer also works on macOS and on other Python versions.
if "$VPY" -m pip install --quiet --no-index --find-links "$HERE/wheels" \
     -r "$PREFIX/app/backend/$REQS" 2>/dev/null; then
  say "Installed dependencies from bundled wheels (offline)"
else
  say "Bundled wheels do not match this platform — installing from PyPI"
  "$VPY" -m pip install --quiet --upgrade pip
  "$VPY" -m pip install --quiet -r "$PREFIX/app/backend/$REQS"
fi

# --- 4. the launcher --------------------------------------------------------
cat > "$PREFIX/bin/mp" <<LAUNCHER
#!/usr/bin/env bash
# Muscle Paradise launcher (generated by install.sh).
set -euo pipefail
PREFIX="$PREFIX"
export MP_DB_PATH="\${MP_DB_PATH:-\$PREFIX/mp.db}"
export MP_STATIC_DIR="\$PREFIX/app/studio"
export MP_HOST="\${MP_HOST:-127.0.0.1}"
export MP_PORT="\${MP_PORT:-$PORT}"
VPY="\$PREFIX/venv/bin/python"
cd "\$PREFIX/app/backend"

case "\${1:-start}" in
  init)   shift; exec "\$VPY" -m app.bootstrap "\$@" ;;
  demo)   shift; exec "\$VPY" -m app.seed_demo "\$@" ;;
  test)   shift
          "\$VPY" -c "import pytest" 2>/dev/null || {
            echo "pytest is not installed. Re-run the installer with --with-tests," >&2
            echo "or: \"\$VPY\" -m pip install -r \"\$PREFIX/app/backend/requirements.txt\"" >&2
            exit 3; }
          exec "\$VPY" -m pytest "\$@" ;;
  start)  shift; exec "\$VPY" -m uvicorn app.main:create_app_from_env --factory \\
            --host "\$MP_HOST" --port "\$MP_PORT" ;;
  *) echo "usage: mp [start|init|demo|test]" >&2; exit 2 ;;
esac
LAUNCHER
chmod +x "$PREFIX/bin/mp"

# --- 5. done ---------------------------------------------------------------
say "Installed Muscle Paradise 0.19.0"
cat <<EOF

Next steps
----------
  export PATH="$PREFIX/bin:\$PATH"

  MP_OWNER_PIN=<4-6 digits> mp init     # create your gym + owner account
  mp demo                               # optional: one demo athlete (MP-DEMO-1 / 1234)
  mp start                              # serve on http://127.0.0.1:$PORT

Then open http://127.0.0.1:$PORT and sign in as owner, or switch to
"ورزشکار" and use MP-DEMO-1 / 1234.

Your data stays in $PREFIX/mp.db — nothing leaves this machine.
EOF
