import {afterEach,describe,expect,it} from 'vitest';import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import http from 'node:http';import {AppDatabase} from '../electron/db';import {SettingsService} from '../electron/services/SettingsService';import {retry} from '../electron/utils/retry';import {OllamaService} from '../electron/services/OllamaService';import {UploadQueue} from '../electron/services/UploadQueue';import type {DownloadService} from '../electron/services/DownloadService';import type {YouTubeService} from '../electron/services/YouTubeService';import {QuotaService} from '../electron/services/QuotaService';import {ChannelMonitor} from '../electron/services/ChannelMonitor';import {ChannelsRepository} from '../electron/db/repositories/channels.repo';import {parseSrt} from '../electron/services/WhisperService';import {cronDue,cronMatches,isValidCron} from '../electron/utils/cron';
const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true})});
describe('database and settings',()=>{it('migrates all tables and round-trips settings',()=>{const root=mkdtempSync(path.join(tmpdir(),'yt-uploader-'));roots.push(root);const database=new AppDatabase(path.join(root,'test.db'));const tables=database.db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all() as Array<{name:string}>;for(const table of ['settings','user_account','channels','synced_videos','clips','upload_history','job_log'])expect(tables.some(row=>row.name===table)).toBe(true);const settings=new SettingsService(database.db);expect(settings.set({defaultPrivacy:'private'}).defaultPrivacy).toBe('private');const channel=database.db.prepare("INSERT INTO channels(youtube_channel_id,channel_name) VALUES('UCtest','Test')").run();database.db.prepare("INSERT INTO synced_videos(channel_id,source_video_id) VALUES(?, 'v1')").run(channel.lastInsertRowid);database.db.prepare("INSERT INTO clips(start_time,end_time) VALUES(0,10)").run();database.db.prepare("INSERT INTO upload_history(status) VALUES('success')").run();database.db.prepare("INSERT INTO job_log(message) VALUES('ok')").run();database.db.prepare("INSERT INTO user_account(id,email) VALUES(1,'test@example.com')").run();database.close()})});
describe('retry',()=>{it('succeeds after two failures',async()=>{let count=0;await expect(retry(async()=>{count++;if(count<3)throw new Error('temporary');return'ok'},{attempts:3,baseDelayMs:1})).resolves.toBe('ok')});it('fails after configured attempts',async()=>{let count=0;await expect(retry(async()=>{count++;throw new Error('fail')},{attempts:5,baseDelayMs:1})).rejects.toThrow('fail');expect(count).toBe(5)})});
describe('ollama',()=>{it('returns running false when unavailable',async()=>{expect((await new OllamaService('http://127.0.0.1:1').status()).running).toBe(false)});it('reads models from a mock server',async()=>{const server=http.createServer((_req,res)=>{res.setHeader('content-type','application/json');res.end(JSON.stringify({models:[{name:'mock:latest'}]}))});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();if(!address||typeof address==='string')throw new Error('mock failed');expect(await new OllamaService(`http://127.0.0.1:${address.port}`).status()).toEqual({running:true,models:['mock:latest']});server.close()})});

describe('upload queue',()=>{
  it('persists and uploads a local file',async()=>{const root=mkdtempSync(path.join(tmpdir(),'yt-queue-'));roots.push(root);const source=path.join(root,'clip.mp4');writeFileSync(source,'synthetic');const database=new AppDatabase(path.join(root,'queue.db'));const downloads={} as DownloadService;let uploads=0;const youtube={upload:async(_file:string,_input:unknown,callbacks:{onProgress:(percent:number)=>void})=>{uploads++;callbacks.onProgress(100);return{id:'video-1',url:'https://youtu.be/video-1'}}} as unknown as YouTubeService;const queue=new UploadQueue(database.db,downloads,youtube,path.join(root,'tmp'),()=>false);const done=new Promise<{error?:string}>((resolve)=>queue.once('done',resolve));queue.enqueue({localPath:source,sourceTitle:'Clip',title:'Clip #Shorts',privacy:'private'},'clipper');await expect(done).resolves.not.toHaveProperty('error');expect(uploads).toBe(1);const row=database.db.prepare('SELECT status,uploaded_video_id FROM synced_videos').get() as {status:string;uploaded_video_id:string};expect(row).toEqual({status:'success',uploaded_video_id:'video-1'});database.close()});

  it('restores interrupted queued jobs after a restart',async()=>{const root=mkdtempSync(path.join(tmpdir(),'yt-restore-'));roots.push(root);const source=path.join(root,'clip.mp4');writeFileSync(source,'synthetic');const file=path.join(root,'restore.db');const first=new AppDatabase(file);first.db.prepare("INSERT INTO synced_videos(source_video_id,source_title,upload_type,privacy,status,payload_json,downloaded_path) VALUES('v-int','Interrupted','single','unlisted','uploading',?,?)").run(JSON.stringify({localPath:source,sourceTitle:'Interrupted',title:'Interrupted'}),source);first.close();const database=new AppDatabase(file);let uploads=0;const youtube={upload:async(_file:string,_input:unknown,callbacks:{onProgress:(percent:number)=>void})=>{uploads++;callbacks.onProgress(100);return{id:'video-2',url:'https://youtu.be/video-2'}}} as unknown as YouTubeService;const queue=new UploadQueue(database.db,{} as DownloadService,youtube,path.join(root,'tmp'),()=>false);const done=new Promise<{error?:string}>((resolve)=>queue.once('done',resolve));await expect(done).resolves.not.toHaveProperty('error');expect(uploads).toBe(1);const row=database.db.prepare("SELECT status FROM synced_videos WHERE source_video_id='v-int'").get() as {status:string};expect(row.status).toBe('success');database.close()});

  it('runs download and upload stages in separate pools with configured concurrency',async()=>{const root=mkdtempSync(path.join(tmpdir(),'yt-pools-'));roots.push(root);const database=new AppDatabase(path.join(root,'pools.db'));let concurrentDownloads=0;let peakDownloads=0;const downloads={metadata:async(url:string)=>({id:`id-${url}`,title:`Title ${url}`,description:'',thumbnail:'',channel:'c',duration:1,viewCount:0,url}),download:async(url:string,dir:string)=>{concurrentDownloads++;peakDownloads=Math.max(peakDownloads,concurrentDownloads);await new Promise(resolve=>setTimeout(resolve,40));concurrentDownloads--;const file=path.join(dir,'video.mp4');writeFileSync(file,'x');return file}} as unknown as DownloadService;const youtube={upload:async(_f:string,_i:unknown,callbacks:{onProgress:(p:number)=>void})=>{callbacks.onProgress(100);return{id:'ok',url:'https://youtu.be/ok'}}} as unknown as YouTubeService;const queue=new UploadQueue(database.db,downloads,youtube,path.join(root,'tmp'),()=>false,()=>({download:2,upload:1}));let finished=0;const all=new Promise<void>(resolve=>queue.on('done',()=>{finished++;if(finished===3)resolve()}));queue.enqueue({url:'a'},'batch');queue.enqueue({url:'b'},'batch');queue.enqueue({url:'c'},'batch');await all;expect(peakDownloads).toBeLessThanOrEqual(2);expect(peakDownloads).toBeGreaterThanOrEqual(2);expect(database.db.prepare("SELECT COUNT(*) count FROM synced_videos WHERE status='success'").get()).toEqual({count:3});database.close()});

  it('cancels an active job through its abort signal',async()=>{const root=mkdtempSync(path.join(tmpdir(),'yt-cancel-'));roots.push(root);const database=new AppDatabase(path.join(root,'cancel.db'));const downloads={metadata:async(url:string)=>({id:'id',title:'t',description:'',thumbnail:'',channel:'c',duration:1,viewCount:0,url}),download:(_url:string,_dir:string,_q:string,_p:unknown,signal?:AbortSignal)=>new Promise((_,reject)=>{signal?.addEventListener('abort',()=>reject(new Error('Cancelled')))})} as unknown as DownloadService;const queue=new UploadQueue(database.db,downloads,{} as YouTubeService,path.join(root,'tmp'),()=>false);const done=new Promise<{error?:string}>(resolve=>queue.once('done',resolve));const handle=queue.enqueue({url:'https://example.com/watch?v=x'});setTimeout(()=>queue.cancel(handle.jobId),50);const result=await done;expect(result.error).toBe('Cancelled');const row=database.db.prepare('SELECT status FROM synced_videos').get() as {status:string};expect(row.status).toBe('cancelled');database.close()});
});

describe('quota',()=>{it('tracks daily usage and blocks when exhausted',()=>{const root=mkdtempSync(path.join(tmpdir(),'yt-quota-'));roots.push(root);const database=new AppDatabase(path.join(root,'quota.db'));const quota=new QuotaService(database.db,3000);quota.require(1600);quota.consume(1600);expect(quota.state()).toMatchObject({used:1600,remaining:1400});expect(()=>quota.require(1600)).toThrow(/quotaExceeded/);database.close()})});

describe('cron',()=>{
  it('validates five-field expressions',()=>{expect(isValidCron('*/15 * * * *')).toBe(true);expect(isValidCron('0 6 * * 1-5')).toBe(true);expect(isValidCron('61 * * * *')).toBe(false);expect(isValidCron('* * *')).toBe(false)});
  it('matches specific instants',()=>{const date=new Date(2026,0,5,6,30);expect(cronMatches('30 6 * * *',date)).toBe(true);expect(cronMatches('0 6 * * *',date)).toBe(false);expect(cronMatches('*/10 * * * 1',date)).toBe(true)});
  it('reports due windows between two instants',()=>{const base=new Date(2026,0,5,6,0).getTime();expect(cronDue('30 6 * * *',base,base+60*60*1000)).toBe(true);expect(cronDue('30 7 * * *',base,base+60*60*1000)).toBe(false)});
});

describe('whisper srt parsing',()=>{it('parses whisper.cpp SRT output into cues',()=>{const cues=parseSrt('1\n00:00:00,000 --> 00:00:02,500\nHello world\n\n2\n00:00:02,500 --> 00:00:05,000\nSecond line\n');expect(cues).toEqual([{start:0,end:2.5,text:'Hello world'},{start:2.5,end:5,text:'Second line'}])})});

describe('channel monitor',()=>{
  const makeMonitorDatabase=(root:string)=>{const database=new AppDatabase(path.join(root,'monitor.db'));database.db.prepare("INSERT INTO channels(youtube_channel_id,channel_name,last_checked_at) VALUES('UCmon','Mon','2020-01-01T00:00:00.000Z')").run();return database};
  it('applies persisted exponential backoff after failures',async()=>{const root=mkdtempSync(path.join(tmpdir(),'yt-mon-'));roots.push(root);const database=makeMonitorDatabase(root);const channels=new ChannelsRepository(database.db);const downloads={playlist:async()=>{throw new Error('network down')}} as unknown as DownloadService;const queue={db:database.db,enqueue:()=>({jobId:'x'})} as unknown as UploadQueue;const monitor=new ChannelMonitor(channels,downloads,queue,()=>undefined);await monitor.tick(1);const first=database.db.prepare('SELECT consecutive_failures,next_retry_at,last_error FROM channels WHERE id=1').get() as {consecutive_failures:number;next_retry_at:string;last_error:string};expect(first.consecutive_failures).toBe(1);expect(first.last_error).toContain('network down');expect(Date.parse(first.next_retry_at)).toBeGreaterThan(Date.now());await monitor.tick(1);const second=database.db.prepare('SELECT consecutive_failures FROM channels WHERE id=1').get() as {consecutive_failures:number};expect(second.consecutive_failures).toBe(2);database.close()});
  it('stores a response fingerprint and skips unchanged listings',async()=>{const root=mkdtempSync(path.join(tmpdir(),'yt-etag-'));roots.push(root);const database=makeMonitorDatabase(root);const channels=new ChannelsRepository(database.db);let calls=0;const downloads={playlist:async()=>{calls++;return[{id:'vid1',title:'One',description:'',thumbnail:'',channel:'Mon',duration:10,viewCount:0,url:'https://youtube.com/watch?v=vid1'}]}} as unknown as DownloadService;const enqueued:string[]=[];const queue={db:database.db,enqueue:(input:{url?:string})=>{enqueued.push(input.url??'');return{jobId:'x'}}} as unknown as UploadQueue;database.db.prepare('UPDATE channels SET auto_upload=1 WHERE id=1').run();const monitor=new ChannelMonitor(channels,downloads,queue,()=>undefined);await monitor.tick(1);expect(enqueued.length).toBe(1);const row=database.db.prepare('SELECT etag FROM channels WHERE id=1').get() as {etag:string};expect(row.etag).toMatch(/^[0-9a-f]{64}$/);await monitor.tick(1);expect(calls).toBe(2);expect(enqueued.length).toBe(1);database.close()});
});
